name: CI
on: [push, pull_request]
jobs:
  build-linux:
    name: Python (${{ matrix.python-version }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["2.7", "3.6", "3.7", "3.8", "3.9"]
    steps:
    - uses: actions/checkout@v2

    - name: Monolith Workflow
      run: |
        wget -q http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
        bash miniconda.sh -b -p $HOME/miniconda
        export PATH=$HOME/miniconda/bin:$PATH
        conda update conda --yes
        conda create --name testenv --yes python=${{ matrix.python-version }} pip six pytest pytest-runner pytest-cov pytest-runner
        source activate testenv
        pip install .
        python setup.py test --addopts " --cov=metar"
        if [[ ${{ matrix.python-version }} == "3.8" ]]; then
          pip install codecov
          codecov
        fi
